apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: leandrole8/conversao-peso:v1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always